{% set version = '0.0.7' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sever
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sever_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sever/sever_{{ version }}.tar.gz
  sha256: 35a02e6328c651ad369b2a1ab4b04655a3757a0dae68e803d57485818d9b4c82

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-htmltools
    - r-shiny
  run:
    - r-base
    - r-cli
    - r-htmltools
    - r-shiny

test:
  commands:
    - $R -e "library('sever')"           # [not win]
    - "\"%R%\" -e \"library('sever')\""  # [win]

about:
  home: https://sever.john-coene.com/
  license: MIT
  summary: Customise 'Shiny' disconnected screens as well as sanitize error messages to make
    them clearer and friendlier to the user.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - Shelnutt2
    - conda-forge/r

# Package: sever
# Title: Customise 'Shiny' Disconnected Screens and Error Messages
# Version: 0.0.7
# Date: 2021-07-14
# Authors@R: person(given = "John", family = "Coene", role = c("aut", "cre"), email = "jcoenep@gmail.com")
# Description: Customise 'Shiny' disconnected screens as well as sanitize error messages to make them clearer and friendlier to the user.
# License: MIT + file LICENSE
# Encoding: UTF-8
# RoxygenNote: 7.1.1
# Imports: cli, shiny, htmltools
# URL: https://sever.john-coene.com/
# BugReports: https://github.com/JohnCoene/sever/issues
# NeedsCompilation: no
# Packaged: 2021-07-14 18:38:02 UTC; jp
# Author: John Coene [aut, cre]
# Maintainer: John Coene <jcoenep@gmail.com>
# Repository: CRAN
# Date/Publication: 2021-07-14 18:50:02 UTC
